spring:
  data:
    redis:
      timeout: 10s # 超時時間
      password: X!h1bIt@2024Redis-kstage
      cluster:
        refresh:
          adaptive: true
          period: 30s
        nodes:  
          - 52.221.134.116:6379  # cluster1 主節點
          - 52.221.134.116:6380  # cluster1 從節點
          - 52.221.134.116:6381  # cluster1 從節點
          - 54.179.45.249:6382  # cluster2 主節點
          - 54.179.45.249:6383  # cluster2 從節點
          - 54.179.45.249:6384  # cluster2 從節點
          - 54.251.19.86:6385  # cluster3 主節點
          - 54.251.19.86:6386  # cluster3 從節點
          - 54.251.19.86:6387  # cluster3 從節點
        max-redirects: 5       # 重定向的最大次數
      lettuce:
        shutdown-timeout: 1s
        pool:
          max-active: 50      # 最大連接數
          max-idle: 30         # 最大空閒連接數
          min-idle: 20         # 最小空閒連接數
          max-wait: 5s         # 連接池阻塞最大等待時間
          time-between-eviction-runs: 5s  # 空閒物件逐出執行緒的執行頻率