# GitLab CI/CD Configuration File
# This file defines the continuous integration and deployment pipeline for the project

# Define the stages of the pipeline in order of execution
stages:
  - notify_approval
  - deploy
  - notify

# notify_approval:
#   stage: notify_approval
#   image: python:3.9-slim
#   tags:
#     - docker
#   before_script:
#     - pip install --no-cache-dir -r requirements.txt
#   script:
#     - python discord_notify.py "Nacos設定異動, 執行更新?（待批准)" "success"
#   when: on_success
#   only:
#     - main

notify_approval:
  stage: notify_approval
  image: python:3.9-slim
  tags:
    - docker
  variables:          
    DISCORD_MESSAGE_CONTENT: "✅ ** Nacos設定異動,待批准! **"
    DISCORD_EMBED_COLOR: 3066993 # 綠色
  before_script:
    - pip install --no-cache-dir -r requirements.txt
  script:
    - python discord_notify.py
  when: on_success
  only:
    - main


# Deploy Nacos Configuration
deploy_nacos_config:
  stage: deploy
  image: python:3.9-slim
  tags:
    - docker
  before_script:
    - pip install --no-cache-dir -r requirements.txt
  script:
    - chmod +x *.sh
    - python nacos_backup.py
    - python nacos_setup.py
    - sleep 2
    - python nacos_diff.py
  artifacts:
    paths:
      - export/

  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - if: '$CI_COMMIT_TAG'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
      when: manual

notify_success:
  stage: notify
  image: python:3.9-slim
  tags:
    - docker
  variables:          # 透過變數將「參數」傳遞給 Python 腳本
    DISCORD_MESSAGE_CONTENT: "✅ ** Nacos配置更新成功! **"
    DISCORD_EMBED_COLOR: 3066993 # 綠色
  before_script:
    - pip install --no-cache-dir -r requirements.txt
  script:
    - python discord_notify.py
  when: on_success
  only:
    - main

notify_failure:
  stage: notify
  image: python:3.9-slim
  tags:
    - docker
  variables:
    DISCORD_MESSAGE_CONTENT: "❌ ** Nacos配置更新失敗! **"
    DISCORD_EMBED_COLOR: 15158332 # 紅色
  before_script:
    - pip install --no-cache-dir -r requirements.txt
  script:
    - python discord_notify.py
  when: on_failure
  only:
    - main
